name: sync-upstream

on:
  workflow_dispatch:
  schedule:
    # 03:00 JST = 18:00 UTC (previous day)
    - cron: "0 18 * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure admin actor
        uses: actions/github-script@v7
        with:
          script: |
            const actor = context.actor;
            const { data } = await github.rest.repos.getCollaboratorPermissionLevel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: actor,
            });
            if (data.permission !== "admin") {
              core.setFailed(`このワークフローはリポジトリ管理者のみ実行できます (権限: ${data.permission}).`);
            }
      - name: Checkout develop-working
        uses: actions/checkout@v4
        with:
          ref: develop-working
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.2.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        working-directory: .tiramiss
        run: pnpm install --frozen-lockfile

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync upstream
        working-directory: .tiramiss
        env:
          CI: true
        run: pnpm run sync-upstream
